export const adminPaths = {
  users: 'users',
  articles: 'articles',
  log: 'log',
  memberships: 'memberships',
  membershipHistory: 'memberships/:username',
  reconcile: 'memberships/reconcile',
  payments: 'payments',
  tips: 'tips',
  refund: 'payments/:id/refund',
  suspendToggle: 'users/:username/suspend-toggle',
  role: 'users/:username/role',
  hideToggle: 'articles/:slug/hide-toggle',
  rootPath: '/admin',
  usersPath: '/admin/users',
  articlesPath: '/admin/articles',
  logPath: '/admin/log',
  membershipsPath: '/admin/memberships',
  reconcilePath: '/admin/memberships/reconcile',
  paymentsPath: '/admin/payments',
  tipsPath: '/admin/tips',
  getSuspendTogglePath: (username: string) => `/admin/users/${username}/suspend-toggle`,
  getRolePath: (username: string) => `/admin/users/${username}/role`,
  getHideTogglePath: (slug: string) => `/admin/articles/${slug}/hide-toggle`,
  getMembershipHistoryPath: (username: string) => `/admin/memberships/${username}`,
  getRefundPath: (id: number) => `/admin/payments/${id}/refund`,
};
